name: Publish /ner-calculator to GitHub Pages
on:
  push:
    branches: [ main ]
    paths:
      - ner-calculator/**
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ner-calculator
      - uses: actions/deploy-pages@v4
